//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1Chess_Srv.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public System.Guid UserId { get; set; }
        public int ProfileIdx { get; set; }
        public System.Guid FriendUserId { get; set; }
        public int FriendProfileIdx { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
