//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1Chess_Srv.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RelatedId { get; set; }
        public string PiecePos { get; set; }
        public string Script { get; set; }
        public Nullable<bool> Rated { get; set; }
        public string TimeInc { get; set; }
        public Nullable<int> TimeAmt { get; set; }
        public Nullable<System.DateTime> StartDT { get; set; }
        public Nullable<System.DateTime> LastActionDT { get; set; }
        public string Sts { get; set; }
        public string EndSts { get; set; }
        public Nullable<bool> IsOver { get; set; }
        public Nullable<System.DateTime> OverDT { get; set; }
        public Nullable<System.Guid> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public Nullable<System.Guid> ChangeUserId { get; set; }
        public Nullable<System.DateTime> ChangeDT { get; set; }
    }
}
