//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1Chess_Srv.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public System.Guid Id { get; set; }
        public bool IsAnonymous { get; set; }
        public bool IsJustRegistered { get; set; }
        public bool IsJustLoggedIn { get; set; }
        public bool IsJustLoggedOut { get; set; }
        public string EmailUserId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> ProfileIdx { get; set; }
        public Nullable<System.Guid> DeviceId { get; set; }
        public string IPAddress { get; set; }
        public string Code { get; set; }
        public string Msg { get; set; }
        public Nullable<System.Guid> URLId { get; set; }
        public Nullable<System.Guid> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string CreateMod { get; set; }
        public Nullable<System.Guid> ChangeUserId { get; set; }
        public Nullable<System.DateTime> ChangeDT { get; set; }
        public string ChangeMod { get; set; }
    }
}
