//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1Chess_Srv.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Url
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Action { get; set; }
        public string Route { get; set; }
        public string View { get; set; }
        public string Paypal { get; set; }
        public Nullable<System.Guid> GameId { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDT { get; set; }
        public System.Guid ChangeUserId { get; set; }
        public System.DateTime ChangeDT { get; set; }
    }
}
