//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1Chess_Srv.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGame
    {
        public System.Guid UserId { get; set; }
        public int ProfileIdx { get; set; }
        public System.Guid GameId { get; set; }
        public Nullable<System.Guid> fURLParmId { get; set; }
        public bool RematchSent { get; set; }
        public string Sts { get; set; }
        public string GameName { get; set; }
        public bool MyTurn { get; set; }
        public Nullable<bool> PlayingAsWhite { get; set; }
        public Nullable<bool> IWon { get; set; }
        public Nullable<int> RatingBefore { get; set; }
        public Nullable<int> RatingAfter { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid ChangeUserId { get; set; }
        public System.DateTime ChangeDate { get; set; }
    }
}
