//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1Chess_Srv.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid Id { get; set; }
        public string EmailAddress { get; set; }
        public string EmailAddressToLower { get; set; }
        public string EmailConfirmCode { get; set; }
        public string Password { get; set; }
        public string PasswordToLower { get; set; }
        public bool IsOnline { get; set; }
        public Nullable<System.Guid> ConnectionId { get; set; }
        public int ProfileIdxDefault { get; set; }
        public string MembershipLevel { get; set; }
        public Nullable<System.DateTime> MembershipExpiration { get; set; }
        public string Role { get; set; }
        public string PhoneCarrier { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public string PhoneConfirmCode { get; set; }
        public bool Opts_EmailAlerts { get; set; }
        public bool Opts_PhoneAlerts { get; set; }
        public bool Opts_AudioOn { get; set; }
        public bool Opts_ClockShow { get; set; }
        public Nullable<bool> Opts_PostToFacebook { get; set; }
        public System.DateTime LastActivityDT { get; set; }
        public System.DateTime CreateDT { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime ChangeDT { get; set; }
        public System.Guid ChangeUserId { get; set; }
    }
}
